version: "3.3"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6370:6379"

  app:
    build:
      dockerfile: Dockerfile
    environment:
      - TG_TOKEN=""
      - CHAT_ID=1234,1235
