version: "3.3"

services:
  # only prod
  telegram-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      # TELEGRAM_API_ID or TELEGRAM_API_HASH get in https://my.telegram.org/
      - TELEGRAM_API_ID=
      - TELEGRAM_API_HASH=

      - TELEGRAM_FILTER=0/BOT_ID
    ports:
      - 8081:8081

  mongo:
    image: mongo:latest
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
