[tool.poetry]
name = "hoba-hoba"
version = "1.0.0"
description = ""
authors = ["Denis Malin <denis@malina.page>"]
license = "GPL-3.0 License"

[tool.poetry.dependencies]
python = "^3.9"
motor = "^2.3.1"
pydantic = "^1.8.1"
uvloop = "^0.15.2"
aiohttp = "^3.7.4"
cchardet = "^2.1.7"
aiodns = "^2.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
